### ISSUE TITLE
Small things in mada-0.3.zip

### ISSUE THREAD

**Issue by davelab6** [alif-type/mada#6] opened 2016-03-11 05:04 UTC
- [x] In `mada-0.3.zip` there are 3 font files in OTF and TTF:
- mada-black.otf
- mada-medium.otf
- mada-thin.otf

These should have the filenames
- Mada-Black.otf 
- Mada-Regular.otf 
- Mada-Thin.otf

and same for the TTFs. I made some notes on this in https://github.com/googlefonts/gf-docs/blob/master/ProjectChecklist.md#instance-and-file-naming
- [x] The `head.fontRevision` is `0.29999` but this should be 1.x because some systems will reject fonts with a version less than 1.0. I made some notes on this in https://github.com/googlefonts/gf-docs/blob/master/ProjectChecklist.md#versioning
- [x] In Black, the macStyle bold bit should not be set. 
- [x] The copyright notice in the fonts is currently 
  
  Portions copyright © 2015-2016, Khaled Hosny (&lt;khaledhosny@eglug.org&gt;). Portions copyright 2010, 2012, 2014 Adobe Systems Incorporated (http://www.adobe.com/), with Reserved Font Name 'Source'.

This string should be ascii, and since there are multiple copyright holders, 

Please set it up like https://github.com/NDISCOVER/Arima-Font 
- [x] In that release zip, the README is blank
- [x] The `name` table is not set up for Black and Thin to work on Windows GDI, which is a core requirement :) https://github.com/googlefonts/gf-docs/blob/master/ProjectChecklist.md#instance-and-file-naming has details
- [x] Mada-Thin.ttf os/2 usWeightClass is 100 but should be 120
- [x] Mada-Thin 'hmtx' '.notdef' lsb should be 0 but is 33
- [x] Mada-Regular.ttf fsType expected 0 but is 8
- [x] Mada-Regular.ttf 'hmtx' '.notdef' should be 0 but is 33

**Comment by khaledhosny** [comment] 2016-03-11 08:07
- I like to keep using all lowercase file names, I’ve always done that and it spares me thinking about/remembering the right capitalisation.
- Medium is because it is the medium (500) weight, I might add a lighter regular (400) one day.
- I can bump the version, but what systems do actually look into font versions, let alone reject fonts based on them (just curious).
- Why the Black’s macStyle should not be set to bold?
- Why the copyright needs to be ASCII (apart from the one in the CFF table, which I’ll fix)?
- This font has as its “Copyright 2015 The Arima Project Authors (info@ndiscovered.com)”, is this what you want? I don’t see how this is much of an improvement given it omits all copyright notices and refers to an undefined list of authors, not to mention no RFN (SSP has it, blame SIL).
- Bug in the build script, next release will have it.

**Comment by davelab6** [comment] 2016-03-11 12:20
If you don't change this then I will need to rename it for the files Google distributes, because the Google Fonts engineers wants the filenames to be canonical and match PS names, and Google's distribution will be de facto the most commonly downloaded and used version, so if yours doesn't match, it will annoy users who do get it from your release.

I as Google will rework the metadata, because many systems including Google's require a 400 style. Ditto.

I forget which systems reject fonts with a version less than 1.0; I think it was MS Word. 

Black’s macStyle should not be set to bold because it causes style selection problems on Android, at least up to the present version. That will annoy users.

The copyright needs to be ASCII because the one in the CFF table must be ASCII and it is helpful for them to all match. Again, I will change this for Google's version.

In the case there is an RFN, please retain the TFN like `Copyright 2015 The Mada Project Authors, with Reserved Font Name "Source". Source is a trademark of Adobe Systems Incorporated in the United States and/or other countries.` The list of authors is defined in the repo.

**Comment by khaledhosny** [comment] 2016-03-11 15:16
OK, will rename the files, not a big deal.
I guess I should interpolate a regular a bold weights, that was the intention from the start. Let me see if I can get it working this time.

The copyright in the CFF font is now ASCII, though it shouldn’t matter for you since you will be using the TTF versions and requiring ASCII for name table entries is an unnecessary and unjustified limitation IMO.

I still don’t see how dropping the individual copyright holders brings us any value, can you at least tell me what is the rationale here?

**Comment by davelab6** [comment] 2016-03-11 17:03
> OK, will rename the files, not a big deal. I guess I should interpolate a regular a bold weights, that was the intention from the start. Let me see if I can get it working this time.

Great!

> The copyright in the CFF font is now ASCII, though it shouldn’t matter for you since you will be using the TTF versions and requiring ASCII for name table entries is an unnecessary and unjustified limitation IMO.

If your source/build process can support this, I'll accept it.

> I still don’t see how dropping the individual copyright holders brings us any value, can you at least tell me what is the rationale here?

It keeps the copyright notice short, simple, and stable; otherwise you'll need to update it each times a new copyright holder sends you a pull request with work subject to copyright. Fonts last for decades and on that time scale looking forwards, libre font projects copyright notice strongs would become very long if we establish a norm where all notices are included on 1 line, and since this year I am ramping up collaboration and shared copyrights in OFL fonts, I want to start setting the norm for collaborative projects up in a good way.

**Comment by davelab6** [comment] 2016-03-11 17:39
Update the top list of items

**Comment by davelab6** [comment] 2016-03-11 17:48
Updated the top list of items again

**Comment by khaledhosny** [comment] 2016-03-11 20:39
OK, I assume you did the required research in this is really a proper way to do attributions. I updated the copyright string, add AUTHORS.txt and CONTRIBUTORS.txt files but I’m not sure what to put there for Adobe copyrights.

**Comment by davelab6** [comment] 2016-03-11 20:59
https://github.com/hafontia/Natan is an example I prepared with that legal files also

**Comment by khaledhosny** [comment] 2016-03-11 21:53
The lsb of `.notdef` is 0 in the “release mode” (which passes the fonts though pyftsubset, I think SMED is screwing something here.

**Comment by khaledhosny** [comment] 2016-03-11 22:09
The spec says Thin is 100, so why 120 (I’ll need to get out of my way to get 120 here since SMED will only produce 100, so I need to convince myself). I guess it is related to GDI.

**Comment by davelab6** [comment] 2016-03-11 22:25
I reviewed the TTF in the release zip, so I'm not sure that this release was made with 'release mode'

Yes, GDI will auto-bold anything with a value of 249 or lower, so 250 is the absolute minimum, and but 100 and 200 should not both be 250, since some UIs will order styles by Weight Class then Alphabetically, and thus not present their logical order.

**Comment by khaledhosny** [comment] 2016-03-11 22:36
The Thin and Black names should be fixed now (Styling Group Name and Styling Link Name is UFO lingo that I don’t know how to map to OpenType name, but I gather it is just the family name vs typographic name stuff).

As for weights, I’m confused, do you want the thin to be 120 or 250, because you wrote the former in the top of the issue. I guess it is the later.

**Comment by davelab6** [comment] 2016-03-12 00:08
Sorry, I have no idea why I wrote 120, lol. I meant 250

**Comment by davelab6** [comment] 2016-05-31 10:50
I see this item, 

>  In Black, the macStyle bold bit should not be set.

is unticked, and indeed, in the Black OTF in the repo right now, it is still set. Please unset it :)

**Comment by davelab6** [comment] 2016-05-31 10:56
Mada-Light.ttf has usWeightClass of 100 but should be 300

fsType should be 0, is 4, for Mada-Light.ttf and Mada-Medium.ttf and Mada-Black.ttf

Mada-Black.ttf fsSelection marked_bold 1 but should not be.

Family naming also need review; please see https://github.com/davelab6/glyphs-export for an example of a name table set up in an ideal way :)

**Comment by davelab6** [comment] 2016-05-31 10:59
Also Mada-Light.ttf fsSelection marked_regular is 1 but should not be.

Mada-Medium.ttf should be Mada-Regular.ttf with weightclass of 400 and with marked_regular of 1 :)

**Comment by khaledhosny** [comment] 2016-05-31 20:18
I think the files in the repository address all issues above, anything missing before I make a new release?

**Comment by davelab6** [comment] 2016-06-08 20:20
The `A` has a remove overlap bug :( 

<img width="659" alt="screen shot 2016-06-08 at 13 20 14" src="https://cloud.githubusercontent.com/assets/261579/15909578/c6d12e9e-2d7b-11e6-9edd-bc64ce874861.png">

**Comment by khaledhosny** [comment] 2016-06-08 20:57
I can’t reproduce this, where are you seeing that? There are overlaps indeed, but I thought they have long not been an issue. Anyway, I’m doing overlap removal now.

**Comment by davelab6** [comment] 2016-06-08 21:22
I download the zip Mada-1.0.zip from the release page and look at the OTFs
and TTFs with OS X Finder Preview

**Comment by khaledhosny** [comment] 2016-06-08 23:04
Can you build from source? I created a 1.1 tag but I’m struggling with binary upload with an exceptionally shitty network connection.

**Comment by davelab6** [comment] 2016-06-08 23:10
The OTFs are now good

**Comment by khaledhosny** [comment] 2016-06-09 00:03
I just published 1.1 release.

**Closed as completed** 2016-06-22 01:38 UTC
